---
extends: default

ignore-from-file: .gitignore

rules:
    comments:
        min-spaces-from-content: 1
    indentation:
        spaces: 4
    line-length:
        max: 90
    truthy:
        check-keys: false
