---
name: Poetry
description: Cache/Install Poetry

runs:
  using: composite
  steps:
    - name: Cache Poetry
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install Poetry
      if: steps.cache-poetry.outputs.cache-hit != true
      shell: bash
      run: curl -sSL https://install.python-poetry.org | python -
